In [94]:
# hr diversity analysis
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
%matplotlib inline

df = pd.read_csv('HRDataset_v13.csv')
df.dropna(how='all', inplace=True)
df.RaceDesc.name = 'Racial Group'
display(df.RaceDesc.value_counts(), df.RaceDesc.value_counts(normalize=True) * 100)

White                               193
Black or African American            57
Asian                                34
Two or more races                    18
American Indian or Alaska Native      4
Hispanic                              4
Name: Racial Group, dtype: int64

White                               62.258065
Black or African American           18.387097
Asian                               10.967742
Two or more races                    5.806452
American Indian or Alaska Native     1.290323
Hispanic                             1.290323
Name: Racial Group, dtype: float64

In [95]:
df = df[df['EmploymentStatus'] == 'Active']
relevant_info = ['RaceDesc', 'GenderID',
                 'PerfScoreID', 'EngagementSurvey']
display(df[relevant_info])

                      RaceDesc  GenderID  PerfScoreID  EngagementSurvey
0    Black or African American       0.0          3.0              2.04
1    Black or African American       1.0          3.0              5.00
2                        White       1.0          3.0              3.90
4                        White       0.0          3.0              5.00
7                        White       0.0          3.0              5.00
..                         ...       ...          ...               ...
298                      White       1.0          3.0              3.84
299                      White       0.0          3.0              5.00
300                      Asian       0.0          3.0              5.00
308                      White       1.0          3.0              5.00
309                      Asian       0.0          3.0              1.06

[182 rows x 4 columns]

In [96]:
df.replace('Black or African American', 0.0, inplace=True)
df.replace('White', 1.0, inplace=True)
df.replace('Asian', 2.0, inplace=True)
df.replace('Hispanic', 3.0, inplace=True)
df.replace('Two or more races', 4.0, inplace=True)
df.replace('American Indian or Alaska Native', 5.0, inplace=True)
display(df[relevant_info])

     RaceDesc  GenderID  PerfScoreID  EngagementSurvey
0         0.0       0.0          3.0              2.04
1         0.0       1.0          3.0              5.00
2         1.0       1.0          3.0              3.90
4         1.0       0.0          3.0              5.00
7         1.0       0.0          3.0              5.00
..        ...       ...          ...               ...
298       1.0       1.0          3.0              3.84
299       1.0       0.0          3.0              5.00
300       2.0       0.0          3.0              5.00
308       1.0       1.0          3.0              5.00
309       2.0       0.0          3.0              1.06

[182 rows x 4 columns]

In [116]:
features = df[relevant_info].values[:, 0:]
labels = df[relevant_info].values[:, -1]
print('array of labels: shape ' + str(np.shape(labels)))
print('array of feature matrix: shape ' + str(np.shape(features)))
print(features)
print(labels)
'''
for i in tqdm(range(12000)):
    dist = np.sum(np.square(val_features[i] - training_features), axis=1)
    near_ind = np.argpartition(dist, 10)[0:10]
    for j in range(10):
        dist10[i][training_gt[near_ind[j]]] += 1

# Save closest 10 neighbor array after completion
np.save("neigh_arr", dist10)
'''

array of labels: shape (182,)
array of feature matrix: shape (182, 4)
[[0.   0.   3.   2.04]
 [0.   1.   3.   5.  ]
 [1.   1.   3.   3.9 ]
 [1.   0.   3.   5.  ]
 [1.   0.   3.   5.  ]
 [1.   0.   1.   2.3 ]
 [5.   1.   3.   3.6 ]
 [4.   1.   3.   3.65]
 [1.   1.   3.   3.98]
 [0.   1.   3.   4.53]
 [4.   1.   1.   1.93]
 [1.   1.   3.   5.  ]
 [0.   0.   3.   2.  ]
 [4.   0.   3.   2.81]
 [2.   1.   3.   1.77]
 [1.   1.   3.   3.31]
 [1.   0.   4.   4.77]
 [0.   1.   3.   1.64]
 [1.   0.   3.   1.72]
 [1.   1.   1.   1.81]
 [1.   1.   3.   2.19]
 [0.   1.   3.   2.94]
 [4.   0.   3.   5.  ]
 [1.   0.   3.   4.28]
 [0.   0.   3.   4.2 ]
 [1.   1.   4.   4.1 ]
 [0.   0.   3.   3.69]
 [0.   0.   3.   2.02]
 [1.   1.   3.   3.01]
 [1.   1.   3.   1.82]
 [0.   1.   3.   2.06]
 [1.   1.   3.   4.5 ]
 [1.   0.   4.   1.12]
 [0.   0.   3.   4.94]
 [1.   0.   3.   4.48]
 [0.   1.   4.   4.28]
 [2.   0.   4.   3.71]
 [1.   0.   3.   3.69]
 [1.   1.   3.   3.04]
 [1.   1.   3.   3.32]
 [1.   0.   3.   5.  ]
 [0.   0.   4.   3.02]
 [1.   0.   3.   1.22]
 [0.   1.   4.   3.76]
 [1.   1.   3.   2.96]
 [3.   1.   2.   2.39]
 [1.   1.   4.   1.99]
 [1.   1.   3.   2.55]
 [1.   0.   3.   1.21]
 [4.   0.   4.   4.64]
 [0.   0.   3.   4.3 ]
 [1.   1.   3.   1.84]
 [1.   1.   3.   2.21]
 [1.   0.   3.   4.11]
 [1.   0.   3.   4.61]
 [1.   1.   1.   1.2 ]
 [1.   0.   3.   3.81]
 [1.   0.   3.   3.31]
 [1.   1.   3.   5.  ]
 [1.   0.   3.   4.83]
 [1.   1.   3.   3.93]
 [1.   1.   4.   5.  ]
 [1.   0.   3.   4.52]
 [1.   1.   3.   4.63]
 [1.   0.   4.   3.66]
 [3.   1.   3.   4.37]
 [1.   0.   3.   4.83]
 [1.   1.   2.   4.13]
 [0.   0.   3.   3.73]
 [1.   0.   4.   5.  ]
 [1.   1.   3.   5.  ]
 [1.   1.   1.   1.12]
 [1.   1.   1.   1.56]
 [4.   0.   4.   3.39]
 [1.   0.   4.   4.76]
 [1.   0.   3.   4.81]
 [1.   0.   4.   5.  ]
 [0.   0.   2.   3.88]
 [1.   0.   3.   5.  ]
 [5.   1.   4.   1.83]
 [1.   0.   3.   3.99]
 [2.   1.   3.   3.38]
 [1.   0.   3.   1.04]
 [2.   0.   4.   1.12]
 [1.   1.   4.   3.02]
 [1.   0.   1.   4.11]
 [0.   0.   3.   4.21]
 [1.   1.   3.   1.51]
 [1.   0.   3.   2.79]
 [1.   1.   3.   4.5 ]
 [1.   1.   3.   5.  ]
 [1.   0.   3.   2.32]
 [1.   1.   3.   5.  ]
 [1.   0.   3.   5.  ]
 [1.   0.   3.   2.79]
 [0.   1.   3.   3.66]
 [1.   0.   3.   5.  ]
 [1.   0.   2.   2.44]
 [2.   0.   3.   1.24]
 [1.   0.   3.   4.84]
 [1.   0.   3.   5.  ]
 [1.   0.   3.   2.73]
 [1.   0.   3.   5.  ]
 [2.   1.   3.   1.83]
 [1.   0.   3.   1.76]
 [0.   0.   3.   3.51]
 [2.   0.   3.   2.77]
 [4.   1.   3.   1.41]
 [0.   1.   3.   4.43]
 [1.   0.   3.   4.73]
 [1.   1.   3.   1.86]
 [1.   1.   3.   2.05]
 [0.   0.   3.   1.66]
 [1.   0.   3.   5.  ]
 [1.   1.   4.   2.86]
 [1.   1.   3.   2.45]
 [2.   1.   3.   1.39]
 [1.   1.   3.   5.  ]
 [2.   0.   3.   2.39]
 [0.   0.   3.   3.58]
 [1.   1.   3.   1.13]
 [1.   0.   3.   1.85]
 [1.   0.   3.   1.94]
 [1.   1.   3.   4.17]
 [0.   1.   3.   2.79]
 [1.   0.   3.   2.55]
 [1.   0.   3.   2.72]
 [1.   0.   3.   3.73]
 [2.   1.   3.   2.61]
 [1.   0.   3.   2.05]
 [0.   0.   3.   3.93]
 [4.   0.   3.   1.05]
 [1.   1.   4.   2.51]
 [1.   0.   3.   5.  ]
 [0.   0.   3.   3.73]
 [1.   0.   3.   4.2 ]
 [1.   1.   3.   3.07]
 [1.   0.   3.   5.  ]
 [0.   1.   2.   4.25]
 [1.   1.   3.   4.36]
 [1.   1.   3.   3.8 ]
 [2.   0.   4.   4.36]
 [0.   0.   3.   4.51]
 [1.   0.   4.   1.51]
 [2.   0.   3.   2.61]
 [1.   1.   3.   2.67]
 [1.   0.   3.   3.4 ]
 [0.   0.   3.   1.49]
 [0.   0.   4.   1.64]
 [1.   0.   3.   4.53]
 [1.   1.   4.   2.41]
 [1.   1.   3.   5.  ]
 [1.   1.   3.   2.08]
 [1.   1.   3.   3.25]
 [5.   0.   4.   4.6 ]
 [1.   0.   3.   5.  ]
 [0.   1.   3.   3.11]
 [4.   1.   3.   3.96]
 [0.   0.   4.   2.55]
 [1.   1.   3.   4.07]
 [1.   0.   2.   1.16]
 [1.   0.   1.   4.59]
 [0.   1.   3.   4.29]
 [1.   1.   3.   3.19]
 [0.   0.   3.   4.  ]
 [1.   0.   3.   4.62]
 [0.   1.   2.   1.62]
 [2.   0.   3.   2.09]
 [2.   1.   3.   5.  ]
 [2.   1.   3.   3.42]
 [1.   1.   3.   1.95]
 [1.   0.   3.   3.04]
 [1.   0.   3.   4.96]
 [0.   0.   3.   3.79]
 [2.   0.   3.   1.53]
 [1.   0.   3.   1.74]
 [1.   1.   4.   2.61]
 [1.   1.   3.   3.84]
 [1.   0.   3.   5.  ]
 [2.   0.   3.   5.  ]
 [1.   1.   3.   5.  ]
 [2.   0.   3.   1.06]]
[2.04 5.   3.9  5.   5.   2.3  3.6  3.65 3.98 4.53 1.93 5.   2.   2.81
 1.77 3.31 4.77 1.64 1.72 1.81 2.19 2.94 5.   4.28 4.2  4.1  3.69 2.02
 3.01 1.82 2.06 4.5  1.12 4.94 4.48 4.28 3.71 3.69 3.04 3.32 5.   3.02
 1.22 3.76 2.96 2.39 1.99 2.55 1.21 4.64 4.3  1.84 2.21 4.11 4.61 1.2
 3.81 3.31 5.   4.83 3.93 5.   4.52 4.63 3.66 4.37 4.83 4.13 3.73 5.
 5.   1.12 1.56 3.39 4.76 4.81 5.   3.88 5.   1.83 3.99 3.38 1.04 1.12
 3.02 4.11 4.21 1.51 2.79 4.5  5.   2.32 5.   5.   2.79 3.66 5.   2.44
 1.24 4.84 5.   2.73 5.   1.83 1.76 3.51 2.77 1.41 4.43 4.73 1.86 2.05
 1.66 5.   2.86 2.45 1.39 5.   2.39 3.58 1.13 1.85 1.94 4.17 2.79 2.55
 2.72 3.73 2.61 2.05 3.93 1.05 2.51 5.   3.73 4.2  3.07 5.   4.25 4.36
 3.8  4.36 4.51 1.51 2.61 2.67 3.4  1.49 1.64 4.53 2.41 5.   2.08 3.25
 4.6  5.   3.11 3.96 2.55 4.07 1.16 4.59 4.29 3.19 4.   4.62 1.62 2.09
 5.   3.42 1.95 3.04 4.96 3.79 1.53 1.74 2.61 3.84 5.   5.   5.   1.06]

'\nfor i in tqdm(range(12000)):\n    dist = np.sum(np.square(val_features[i] - training_features), axis=1)\n    near_ind = np.argpartition(dist, 10)[0:10]\n    for j in range(10):\n        dist10[i][training_gt[near_ind[j]]] += 1\n\n# Save closest 10 neighbor array after completion\nnp.save("neigh_arr", dist10)\n'